### ISSUE TITLE
About STAR dataset

### ISSUE THREAD

**Issue by mhd0528** [aurooj/SHG-VQA#2]
Hi,

Are you still going to release the code for the STAR dataset? Thanks.

**Comment by aurooj** [comment]
Hello, yes. It might take a couple of weeks though.

**Comment by mhd0528** [comment]
Ok, thanks! Looking forward to it. Really interesting work btw.

**Comment by mhd0528** [comment]
Hi, may I ask when this part will be released? Thanks.

**Comment by aurooj** [comment]
@mhd0528 code and data for STAR are uploaded now. Read details [here](https://github.com/aurooj/SHG-VQA)

**Comment by mhd0528** [comment]
Thanks!
