### ISSUE TITLE
Where to find files in SHG-VQA/AGQA/annotations/ ? 

### ISSUE THREAD

**Issue by bashirulazam** [aurooj/SHG-VQA#4]
Hi, 

Where can I find the files that are supposed to be in the annotation folder (SHG-VQA/AGQA/annotations/ )? There are several files mentioned in the README file but I am not able to find the sources of this file. Could you please clarify?

Thanks!

**Comment by aurooj** [comment]
Processed files for agqa are now uploaded in `AGQA/annotations/` folder.
