### ISSUE TITLE
Where is the agqav2/test_balanced.json?

### ISSUE THREAD

**Issue by fake-warrior8** [aurooj/SHG-VQA#6]
Hi, there is only [train_and_val.json](https://drive.google.com/file/d/17_rqCnR9whlXRPd9RfubhPUP8oLCFD4b/view), where is the test_balanced.json?

**Comment by aurooj** [comment]
Thanks for your interest in our work. You can download the AGQA v2 test set from their official website. The direct link is: https://agqa-decomp.cs.washington.edu/data/agqa2/AGQA_balanced.zip

In this folder, test_balanced.txt is the file you are looking for. 
Process the file as mentioned on our github repo in the [preprocessing](https://github.com/aurooj/SHG-VQA/tree/main?tab=readme-ov-file#questions) section. 

You just need to loop over the test_balanced.txt data to keep the dictionary of the fields mentioned in our code repo preprocessing section.

I hope it helps.

**Comment by fake-warrior8** [comment]
> Thanks for your interest in our work. You can download the AGQA v2 test set from their official website. The direct link is: https://agqa-decomp.cs.washington.edu/data/agqa2/AGQA_balanced.zip
> 
> In this folder, test_balanced.txt is the file you are looking for. Process the file as mentioned on our github repo in the [preprocessing](https://github.com/aurooj/SHG-VQA/tree/main?tab=readme-ov-file#questions) section.
> 
> You just need to loop over the test_balanced.txt data to keep the dictionary of the fields mentioned in our code repo preprocessing section.
> 
> I hope it helps.

Thank you for your reply!
